language: cpp
compiler:
  - gcc
  - clang
before_install:
  - if [ "$CXX" = "g++" ]; sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - if [ "$CXX" = "g++" ]; sudo apt-get update -qq; fi
install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
script:
  - cmake CMakeLists.txt && make && make test
branches:
  only:
    - master
